import { MAX_CONNECT_FRAME_BYTES } from "./connect-frame"

const MAX_BRIDGE_ID_CHARACTERS = 128
const MAX_BRIDGE_WIRE_OVERHEAD = '{"kind":"write-frame","id":"","payload":""}'.length
const OPTIONAL_CARRIAGE_RETURN_CHARACTERS = 1

export const MAX_BRIDGE_BINARY_BYTES: number = MAX_CONNECT_FRAME_BYTES
export const MAX_BRIDGE_BASE64_CHARACTERS: number = Math.ceil(MAX_BRIDGE_BINARY_BYTES / 3) * 4
export const MAX_BRIDGE_LINE_LENGTH: number =
  MAX_BRIDGE_BASE64_CHARACTERS +
  MAX_BRIDGE_ID_CHARACTERS +
  MAX_BRIDGE_WIRE_OVERHEAD +
  OPTIONAL_CARRIAGE_RETURN_CHARACTERS
